title: Life is Dount!
author: vertvert123
email: vertvert123@naver.com
description: > # this means to ignore newlines until "show_exerpts:"
  개발실력은 삽질과 비례한다.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: vertvert123
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    email: vertvert123@naver.com
    twitter: 
    github: vertvert123
    linkedIn:  
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed